export const gearCategories = [
  { id: "davullar", name: "Davullar", color: "var(--color-flare)" },
  { id: "perkusyon", name: "Perküsyon", color: "var(--color-volt)" },
  { id: "klavyeler", name: "Klavyeler & Synth", color: "var(--color-paper)", textColor: "var(--color-ink)" },
  { id: "gitarlar-baslar", name: "Gitarlar & Amfiler", color: "var(--color-ink)", border: "var(--color-paper)" },
  { id: "studyo", name: "Stüdyo & Konsol", color: "var(--color-ink)", border: "var(--color-volt)" },
];

export const gearData: Record<string, { title: string; items: string[] }> = {
  davullar: {
    title: "Davullar & Trampetler",
    items: [
      "DW Collector's Series",
      "Pearl Masterworks",
      "Pearl Reference",
      "Yamaha Stage Custom",
      "Yamaha Recording Custom",
      "Yamaha Absolute Maple Custom Hybrid",
      "Tama Starclassic Birch Bubinga Japan",
      "Ludwig American",
      "Gretsch New Classic",
      "Yamaha Absolute AMS1460 Snare",
      "Ludwig Snare (x2)",
      "Pearl Dennis Chambers Signature Snare (x3)",
      "DW Performance Series Snare",
    ],
  },
  perkusyon: {
    title: "Perküsyon",
    items: [
      "Remo Djembe",
      "Gawharet Darbuka",
      "Latin Percussion Timbal (x2)",
      'Latin Percussion Pedrito Martinez Signature Galaxy Series 11", 12" 1/2',
      'Latin Percussion Santana Collection 11", 12" 1/2',
      "Toys, Shaker, Cowbell",
    ],
  },
  klavyeler: {
    title: "Klavyeler & Synth",
    items: [
      "Yamaha Montage M8x",
      "Yamaha Montage M6",
      "Nord Stage 3",
      "Nord Electro 6HP (73 Tuş)",
      "Korg Kronos 3",
      "Yamaha MODX8+",
      "Roland AX-Edge",
    ],
  },
  "gitarlar-baslar": {
    title: "Gitarlar & Amfiler",
    items: [
      "Fender Precision Bass American Pro II",
      "Ernie Ball Music Man StingRay 5",
      "Ibanez JS Series",
      "Kemper Profiler",
      "Fender Twin Reverb (x2)",
      "Fender DeVille",
      "Fender Hot Rod Deluxe",
      "Blackstar HT Stage 100 (x2)",
      "Roland Jazz Chorus 120",
      "Ampeg SVT-4",
      "Ampeg SVT-R Pro",
      "Ampeg Pro Neo PL 410-HLF (x2)",
      "Ampeg Pro Neo PL 410-HLFx (x2)",
      "Ampeg Rocket Bass RB210",
      'Markbass 4x10" (x2)',
      'Markbass 1x15" MBR15 Kabin',
      "Markbass Little Mark",
      "Aguilar AG700",
      "Gallien-Krueger Neo 410",
    ],
  },
  studyo: {
    title: "Stüdyo & Konsol",
    items: [
      "Genelec Studio Monitors",
      "Neve 1073DPA",
      "SSL Pure Drive Octo",
      "Antelope Orion+ 32",
      "Antelope Discrete 8",
      "RME OctaMic II",
      "Behringer Powerplay P16",
      "Kemper Profiler (Rack)",
    ],
  },
};
